FROM python:3.13-slim

# root
RUN apt-get update > /dev/null && \
    apt-get install -y --no-install-recommends apt-utils build-essential pkg-config libxml2-dev libxslt1-dev libpoppler-dev libpoppler-cpp-dev libheif-dev libcairo2-dev > /dev/null && \
    apt-get clean autoclean && apt-get autoremove -y

ARG USER_ID=1000
ARG USER_NAME=terzeron
RUN useradd -u $USER_ID $USER_NAME && \
    mkdir -p /app /books /home/$USER_NAME/.cache/pip /home/$USER_NAME/.local && \
    chown -R $USER_NAME /app /books /home/$USER_NAME/.cache/pip /home/$USER_NAME/.local

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin

# user(1000)
USER $USER_NAME
WORKDIR /app

ENV UV_SYSTEM_PYTHON=1 UV_LINK_MODE=copy UV_PYTHON=python3.13
COPY pyproject.toml uv.lock /app
RUN HOME=/tmp XDG_CACHE_HOME=/tmp/.cache UV_CACHE_DIR=/tmp/uv-cache \
    uv sync --locked --no-editable

COPY logging.conf /app
COPY backend /app/backend
COPY utils /app/utils

VOLUME /books

ENV PATH="/app/.venv/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/home/$USER_NAME/.local/bin:/app/bin:/app/utils"
ENV PYTHONPATH="/app"
ENV TM_BACKEND_PORT=8020

EXPOSE $TM_BACKEND_PORT

CMD ["sh", "-c", "uvicorn backend.main:app --workers 1 --host 0.0.0.0 --reload --port ${TM_BACKEND_PORT}"]
