FROM python:3.11

# root
RUN apt-get update > /dev/null && \
    apt-get install -y --no-install-recommends apt-utils libpoppler-dev libpoppler-cpp-dev libheif-dev libcairo2-dev > /dev/null && \
    apt-get clean autoclean && apt-get autoremove -y

ARG USER=terzeron
RUN useradd -u 1000 $USER && \
    mkdir -p /app /books /home/$USER/.cache/pip /home/$USER/.local && \
    chown -R $USER /app /books /home/$USER/.cache/pip /home/$USER/.local

# user(1000)
USER $USER

WORKDIR /app

COPY requirements.txt /app
COPY logging.conf /app
COPY backend /app/backend
COPY utils /app/utils

RUN pip install -r requirements.txt > /dev/null

VOLUME /books

ENV PATH="$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/home/$USER/.local/bin:/app/bin:/app/utils"
ENV PYTHONPATH="/app"
ENV TM_BACKEND_PORT=8020

EXPOSE $TM_BACKEND_PORT

CMD ["sh", "-c", "uvicorn backend.main:app --workers 1 --host 0.0.0.0 --reload --port ${TM_BACKEND_PORT}"]
