vmType: vz
cpus: 8
memory: 16GiB
disk: 60GiB

images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"

hostResolver:
  enabled: false

dns:
  - 8.8.8.8
  - 1.1.1.1

mounts:
  - location: "~"

containerd:
  system: false
  user: false

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail
      if ! command -v docker &>/dev/null; then
        export DEBIAN_FRONTEND=noninteractive
        curl -fsSL https://get.docker.com | sh
        usermod -aG docker ${LIMA_CIDATA_USER}
      fi

portForwards:
  - guestSocket: /var/run/docker.sock
    hostSocket: "{{.Dir}}/sock/docker.sock"
  - guestPortRange: [1, 65535]
    hostIP: "0.0.0.0"
